### ISSUE TITLE
Issue with models have table_name_prefix on parent module

### ISSUE THREAD

**Issue by singh-ashutosh-007** [jurriaanschrofer/datagaze#1]
Datagaze not able to recognize the table prefix name.?
Below is the error I am getting where it is looking for escrow_banks table instead of ap_escrow_banks table.

>>>> Table 'ashu_developemnt.escrow_banks' doesn't exist (Mysql2::Error)

Below are the example of classes written
module ParentModule
    class EscrowBank < ApRecord
    end
  end

  module ParentModule
    def self.table_name_prefix
      "ap_"
    end
  end

  class ApRecord < ApplicationRecord
    self.abstract_class = true
    connects_to database: { writing: :ap, reading: :ap_replica }
  end

**Comment by jurriaanschrofer** [comment]
Hi @ashutosh-singh-rawat!

Thanks for issue report, I am happy to announce that I have added and deployed the missing functionality to RubyGems (V 0.0.5) :-)

To be exact:
- Datagaze now recognises table_name prefixes, if it is set by the `.table_name_prefix=` method.
- Datagaze also recognises table_name suffixes (set through the equivalent `.table_name_suffix=` method). 
- Datagaze handles above methods correctly for both strings and symbols.

Let me know if you run into more problems, I am happy to help you.

Jurriaan
